# Generated by Django 5.0.7 on 2024-10-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('picture', models.ImageField(blank=True, upload_to='products/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
